### PR TITLE
Covariant return types on copy() methods

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
There's a rumor going around that XOM might support constructs from more recently than 15 years ago.  So here's a patch to make life easier for users of the ``Node.copy()`` method.

**Comment by dmlloyd** [comment]
BTW DocType.java is a real line endings disaster.

**Comment by dmlloyd** [comment]
Some of the lines at LF, some are CRLF. Most editors seem to want to rewrite the whole file to one thing making diff production difficult.

**Comment by elharo** [comment]
Thanks for the PR. I added some tests and docs to match.

**Pull request closed without merging**
